### ISSUE TITLE
If ive kept FindDER= False and ran the whole code is there any way i can find DER after the completion of code?

### ISSUE THREAD

**Issue by saumyaborwankar** [Rehan-Ahmad/MultimodalDiarization#1]

**Comment by Rehan-Ahmad** [comment]
To find DER you can run the lines enclosed in "if FindDER=False", it will compute it. But, before doing that please make sure that you run the script for all the Closeup (1-4) camera streams.

**Comment by saumyaborwankar** [comment]
The reason I asked this was because the code throws an error with file IS1008a when you run it with FindDER=True, attaching a photo of the error
![image](https://user-images.githubusercontent.com/46644513/125892115-462f530c-7417-48a3-8867-5190c9f3312c.png)

**Comment by Rehan-Ahmad** [comment]
Please check your **IS1008a.Closeup4.pickle** file. It seem to be problem with this pickle file. In the figure above, I also didn't find this file.

**Comment by saumyaborwankar** [comment]
Also another side doubt, so as the processing takes too much time, i was thinking of reducing the frame rate of video, so will the results be affected by this?

**Comment by saumyaborwankar** [comment]
> Please check your **IS1008a.Closeup4.pickle** file. It seem to be problem with this pickle file. In the figure above, I also didn't find this file.

Okay give me some time ill check and get back to you.

**Comment by Rehan-Ahmad** [comment]
> Also another side doubt, so as the processing takes too much time, i was thinking of reducing the frame rate of video, so will the results be affected by this?

May be, you can test that scenario as well. The reason to save the face detection pickle is that one should not run face detection again and again if someone need to run the code with some different configuration. closing this issue. Thanks.

**Comment by saumyaborwankar** [comment]
Still the same error 
![image](https://user-images.githubusercontent.com/46644513/125941109-7a0f74f6-de94-4d34-8db6-e2f51a4c3e05.png)

**Comment by saumyaborwankar** [comment]
Also what DER should I be expecting with IS1008a file if you remember the results?

**Comment by Rehan-Ahmad** [comment]
Please use pdb to debug, the issue seems to be with your .pickle or .txt file. Please check my paper for the results.

**Comment by saumyaborwankar** [comment]
Okay thanks
